name: Img Auto Compress

on:
  push:
    branches:
      - main  # 在 main 分支推送时触发
  workflow_dispatch:

jobs:
  # 自动测试作业
  auto-sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pm2 globally
        run: npm install -g pm2

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Clone private repository
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://x-access-token:${PAT}@github.com/Jyf0214/veiled-journeys.git

      - name: Install dependencies globally
        run: |
          pip install -r veiled-journeys/requirements.txt
          sudo apt-get update
          sudo apt-get install -y ffmpeg 
          sudo apt-get install optipng
          sudo apt-get install jpegoptim

      - name: Test veiled-journeys App
        run: |
          cd veiled-journeys
          python download_img.py

      - name: Process Video 
        env:
          PAT_1: ${{ secrets.PAT_1 }}
        run: |
          python src/random_string.py
          git config --global user.name "Jyf0214"
          git config --global user.email "169313142+Jyf0214@users.noreply.github.com" 
          git remote add origin1 https://x-access-token:${PAT_1}@github.com/Jyf0214/blog-index.git && git add data.txt && git commit -m "Add data.txt" && git push origin1 main
          cd veiled-journeys
          pm2 start iloveapi_img_plus.py --interpreter python --name "ImageProcessing"
          chmod +x compress.sh
          ./compress.sh
          chmod +x compress_img.sh
          ./compress_img.sh

      - name: Upload Compressed to Web
        run: |
          cd veiled-journeys
          python 4.py

      - name: Check for finished.task and Run 4_img.py
        run: |
          cd veiled-journeys
          python 4_img.py
              