name: Video Compression Workflow

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # [优化] 增加缓存步骤，缓存 apt 和 pip 的依赖项
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/apt/archives
            ~/.cache/pip
          key: ${{ runner.os }}-deps-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Setup Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Clone veiled-journeys repository
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://x-access-token:${PAT}@github.com/Jyf0214/veiled-journeys.git

      - name: Install Python requirements
        run: |
          pip install -r veiled-journeys/requirements.txt

      - name: Download One Video File from Directory
        run: |
          mkdir -p video_work
          cd veiled-journeys
          python webdav_download.py -a="MyVideos/" -b="../video_work/" -c=1
          cd ..

      - name: Process and Compare Video
        id: process
        run: |
          cd video_work
          ORIGINAL_FILE=$(find . -type f -name "*.mp4" -print -quit)
          
          if [ -z "$ORIGINAL_FILE" ]; then
            echo "::error::No .mp4 file found in the downloaded content!"
            exit 1
          fi
          
          ORIGINAL_FILENAME=$(basename "$ORIGINAL_FILE")
          COMPRESSED_FILE="compressed_${ORIGINAL_FILENAME}"
          
          echo "Processing file: $ORIGINAL_FILENAME"
          echo "Starting FFmpeg encoding with high-efficiency settings..."
          
          # [核心优化] 
          # 1. 将 -preset 从 medium 改为 slow，用更长时间换取更高压缩率。
          # 2. 将 -c:a aac -b:a 128k 改为 -c:a copy，直接复制音轨，保证音质无损并提速。
          ffmpeg -i "$ORIGINAL_FILE" -c:v libx265 -preset veryslow -crf 16 -threads 32 -tag:v hvc1 -c:a copy "$COMPRESSED_FILE"
          
          ORIGINAL_SIZE=$(stat -c%s "$ORIGINAL_FILE")
          COMPRESSED_SIZE=$(stat -c%s "$COMPRESSED_FILE")
          
          echo "Original size: $ORIGINAL_SIZE bytes"
          echo "Compressed size: $COMPRESSED_SIZE bytes"
          
          if [ "$ORIGINAL_SIZE" -le "$COMPRESSED_SIZE" ]; then
            echo "Compressed file is not smaller. Keeping original."
            rm "$COMPRESSED_FILE"
            mv "$ORIGINAL_FILE" "final_output.mp4"
            echo "final_file=video_work/final_output.mp4" >> $GITHUB_OUTPUT
          else
            echo "Compressed file is smaller. Keeping compressed version."
            rm "$ORIGINAL_FILE"
            mv "$COMPRESSED_FILE" "final_output.mp4"
            echo "final_file=video_work/final_output.mp4" >> $GITHUB_OUTPUT
          fi
          cd ..

      - name: Upload Final Video
        env:
          # 为了安全，建议将密码设置为 GitHub Secret
          KOOFR_PASSWORD: ${{ secrets.KOOFR_PASSWORD }}
        run: |
          python veiled-journeys/koofr_upload.py \
            --file "${{ steps.process.outputs.final_file }}" \
            --target "https://jike.teracloud.jp/dav/MyVideos/compressed/"