name: Rclone-Unified Parallel Video Compression

on:
  workflow_dispatch:

env:
  REMOTE_DIR: ${{ github.run_id }}
  WORKFLOW_RUN_ID: ${{ github.run_id }}

jobs:
  # 任务1：分割并缓存（此部分无改动）
  split_and_cache:
    runs-on: ubuntu-latest
    outputs:
      matrix_payload: ${{ steps.split.outputs.matrix_array }}
    steps:
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Clone scripts repository
        env:
          PAT: ${{ secrets.PAT }}
        run: git clone https://x-access-token:${PAT}@github.com/Jyf0214/veiled-journeys.git

      - name: Install Python requirements
        run: pip install -r veiled-journeys/requirements.txt

      - name: Download Original Video
        run: |
          mkdir -p original_video
          python veiled-journeys/webdav_download.py -a="MyVideos/" -b="./original_video/" -c=1

      - name: Split video and generate matrix
        id: split
        run: |
          mkdir -p video_segments
          ORIGINAL_FILE=$(find ./original_video -maxdepth 1 -type f -name "*.mp4" -print -quit)
          ffmpeg -i "$ORIGINAL_FILE" -c copy -f segment -segment_time 20 -reset_timestamps 1 "video_segments/segment_%03d.mp4"
          COUNT=$(ls -1 video_segments/*.mp4 | wc -l)
          echo "count=$COUNT" >> $GITHUB_OUTPUT
          if [ "$COUNT" -gt 0 ]; then
            SEQUENCE=$(seq 0 $(($COUNT - 1)) | tr '\n' ',' | sed 's/,$//')
            JSON_ARRAY="[${SEQUENCE}]"
          else
            JSON_ARRAY="[]"
          fi
          echo "matrix_array=${JSON_ARRAY}" >> $GITHUB_OUTPUT

      - name: Save Original Video and Segments to Cache
        uses: actions/cache/save@v4
        with:
          path: |
            original_video/
            video_segments/
          key: source-files-${{ env.WORKFLOW_RUN_ID }}

  # 任务2：使用Rclone上传压缩片段
  compress_and_upload_to_b2:
    runs-on: ubuntu-latest
    needs: split_and_cache
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        segment_index: ${{ fromJSON(needs.split_and_cache.outputs.matrix_payload) }}
    steps:
      # --- 修正点 1 ---
      - name: Install Dependencies (ffmpeg, rclone)
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          sudo -v ; curl https://rclone.org/install.sh | sudo bash

      - name: Restore Uncompressed Segments from Cache
        uses: actions/cache/restore@v4
        with:
          path: video_segments/
          key: source-files-${{ env.WORKFLOW_RUN_ID }}
          fail-on-cache-miss: true

      # --- 修正点 2 ---
      - name: Configure Rclone
        env:
          B2_KEY_ID: ${{ secrets.B2_KEY_ID }}
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
        run: |
          mkdir -p ~/.config/rclone
          echo "[b2_remote]
          type = b2
          account = ${B2_KEY_ID}
          key = ${B2_APPLICATION_KEY}" > ~/.config/rclone/rclone.conf
      
      - name: Process One Segment
        id: process
        run: |
          mkdir -p compressed_output
          FORMATTED_INDEX=$(printf "%03d" ${{ matrix.segment_index }})
          INPUT_FILE="video_segments/segment_${FORMATTED_INDEX}.mp4"
          OUTPUT_FILE="compressed_output/compressed_${FORMATTED_INDEX}.mp4"
          ffmpeg -i "$INPUT_FILE" -c:v libx265 -preset fast -crf 23 -tag:v hvc1 -c:a copy "$OUTPUT_FILE"
          echo "output_file=$OUTPUT_FILE" >> $GITHUB_OUTPUT

      # --- 修正点 3 ---
      - name: Upload Compressed Segment with Rclone
        run: |
          OUTPUT_FILE=${{ steps.process.outputs.output_file }}
          BASENAME=$(basename "$OUTPUT_FILE")
          # 使用 rclone copyto 将单个文件上传到指定位置
          rclone copyto "$OUTPUT_FILE" "b2_remote:${{ secrets.B2_BUCKET_NAME }}/${{ env.REMOTE_DIR }}/compressed/${BASENAME}"

  # 任务3：从B2下载、合并并上传（此部分逻辑正确，无需改动）
  merge_from_b2_and_upload:
    runs-on: ubuntu-latest
    needs: [split_and_cache, compress_and_upload_to_b2]
    steps:
      - name: Install Dependencies (ffmpeg, rclone)
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          sudo -v ; curl https://rclone.org/install.sh | sudo bash

      - name: Restore Original Video from Cache
        uses: actions/cache/restore@v4
        with:
          path: original_video/
          key: source-files-${{ env.WORKFLOW_RUN_ID }}
          fail-on-cache-miss: true

      - name: Configure Rclone for B2 (with Download URL)
        env:
          B2_KEY_ID: ${{ secrets.B2_KEY_ID }}
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
          B2_DOWNLOAD_URL: ${{ secrets.B2_DOWNLOAD_URL }}
        run: |
          mkdir -p ~/.config/rclone
          echo "[b2_remote]
          type = b2
          account = ${B2_KEY_ID}
          key = ${B2_APPLICATION_KEY}
          download_url = ${B2_DOWNLOAD_URL}" > ~/.config/rclone/rclone.conf

      - name: Download all compressed segments from B2
        run: |
          mkdir -p compressed_segments
          rclone copy "b2_remote:${{ secrets.B2_BUCKET_NAME }}/${{ env.REMOTE_DIR }}/compressed" ./compressed_segments

      - name: Clone and setup upload scripts
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://x-access-token:${PAT}@github.com/Jyf0214/veiled-journeys.git
          pip install -r veiled-journeys/requirements.txt
      
      - name: Merge, Compare and Upload
        run: |
          if ! find ./compressed_segments -mindepth 1 -type f -name "*.mp4" | read; then
            echo "::error::No compressed segments were downloaded from B2."
            exit 1
          fi
          find ./compressed_segments -type f -name "*.mp4" | sort -V | while read -r f; do echo "file '$f'" >> file_list.txt; done
          ffmpeg -f concat -safe 0 -i file_list.txt -c copy final_video.mp4
          
          ORIGINAL_FILE=$(find ./original_video -type f -name "*.mp4")
          MERGED_FILE="final_video.mp4"
          ORIGINAL_SIZE=$(stat -c%s "$ORIGINAL_FILE")
          MERGED_SIZE=$(stat -c%s "$MERGED_FILE")
          FINAL_FILE_PATH="$ORIGINAL_FILE"
          
          if [ -f "$MERGED_FILE" ] && [ "$MERGED_SIZE" -lt "$ORIGINAL_SIZE" ] && [ "$MERGED_SIZE" -gt 0 ]; then
            FINAL_FILE_PATH="$MERGED_FILE"
          fi
          
          python veiled-journeys/gofile_manager.py upload --file "$FINAL_FILE_PATH" --list-file "compressed_videos_list.txt" > /dev/null 2>&1
  
  # 任务4：使用Rclone清理B2上的临时文件
  cleanup_b2:
    runs-on: ubuntu-latest
    needs: merge_from_b2_and_upload
    if: always()
    steps:
      - name: Install Rclone
        run: sudo -v ; curl https://rclone.org/install.sh | sudo bash

      - name: Configure Rclone
        env:
          B2_KEY_ID: ${{ secrets.B2_KEY_ID }}
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
        run: |
          mkdir -p ~/.config/rclone
          echo "[b2_remote]
          type = b2
          account = ${B2_KEY_ID}
          key = ${B2_APPLICATION_KEY}" > ~/.config/rclone/rclone.conf

      # --- 修正点 4 ---
      - name: Purge temporary directory from B2 with Rclone
        run: |
          echo "Purging remote directory: ${{ env.REMOTE_DIR }}"
          # rclone purge 会删除指定目录及其所有内容，是最高效的清理方式
          rclone purge "b2_remote:${{ secrets.B2_BUCKET_NAME }}/${{ env.REMOTE_DIR }}"
          echo "Cleanup complete."