name: Auto-sign

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  auto-sign:
    runs-on: ubuntu-latest
    steps:
      # 步骤 1-3: 保持不变
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Clone private repository (veiled-journeys)
        env:
          PAT: ${{ secrets.GITCODE_TOKEN }}
        run: |
          git clone https://Jyf0214:${PAT}@gitcode.com/Jyf0214/veiled-journeys.git
      - name: Install global dependencies
        run: |
          # 全局只需要安装 cryptography
          pip install cryptography
          # 如果有其他必要全局包，在这里安装
          pip install -r veiled-journeys/requirements.txt
      
      # ========================= 核心修复 =========================
      # 步骤 5: 创建并进入沙箱工作区
      - name: Setup Sandbox Workspace
        run: |
          # 创建一个干净的工作区目录
          mkdir -p Jyf0214_workspace/Jyf0214
          
          # 将启动器和加密仓库移动到工作区内
          mv veiled-journeys/main.py Jyf0214_workspace/Jyf0214/
          mv veiled-journeys/Jyf0214_encrypted Jyf0214_workspace/Jyf0214/
          
          echo "Workspace setup complete."

      # 步骤 6: 在沙箱容器内执行所有任务
      - name: Run all tasks inside the Veiled-Journeys container
        # 直接在搭建好的工作区内运行
        working-directory: ./Jyf0214_workspace/Jyf0214
        env:
          # 提供所有需要的 secrets
          GitHub_Actions: true
          TOTKEN: ${{ secrets.TOKEN }}
          SUBJECT: ${{ secrets.SUBJECT }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          Git_EMAIL: ${{ secrets.TO_EMAIL }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          PHONE: ${{ secrets.PHONE }}
          PASSWORD: ${{ secrets.PASSWORD }}
          Jyf0214_PASSWORD: ${{ secrets.Jyf0214_PASSWORD }}
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing workspace contents:"
          ls -R
          
          # 使用 "here document" 将命令喂给 main.py
          python main.py <<EOF
          python skyland.py
          python smtp.py
          python bingapi.py
          python git.py
          python src/dailymessage.py
          cd Skland
          ls
          if [ ! -f "./TOKEN.txt" ]; then
            echo "Error: Token.txt does not exist."
            exit 1
          fi
     
          pip install --target=./ requests cryptography cffi
          find . -type d -name '*dist-info' -exec rm -rf {} +
          zip -r code.zip .
          python sync.py
          exit
