name: Auto Sign
on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies globally
        run: |
          python -m pip install --upgrade pip
          pip install requests cryptography resend pyyaml rsa huaweicloudsdkfunctiongraph pillow

      - name: Clone private repository
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://x-access-token:${PAT}@github.com/Jyf0214/veiled-journeys.git

      - name: Run veiled-journeys scripts
        env:
          GitHub_Actions: true
          TOTKEN: ${{ secrets.TOKEN }}
          SUBJECT: ${{ secrets.SUBJECT }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          Git_EMAIL: ${{ secrets.TO_EMAIL }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          PHONE: ${{ secrets.PHONE }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          cd veiled-journeys
          python skyland.py
          python smtp.py
          python bingapi.py
          python git.py
          ls
          python webdav_download.py
          ls
          python iloveapi_img_plus.py
          python webdav_upload.py

      - name: Process Auto-Sign App and Deploy to HWAWAI FC
        run: |
          cd veiled-journeys/Auto-Sign
          pip install --target=./ requests rsa pyyaml resend
          find . -type d -name '*dist-info' -exec rm -rf {} +
          zip -r code.zip .
          python sync.py

      - name: Process Skland App and Deploy to HWAWAI FC
        run: |
          # 检查 Token.txt 文件是否存在且内容合法
          cd veiled-journeys/Skland
          ls
          if [ ! -f "./TOKEN.txt" ]; then
            echo "Error: Token.txt does not exist."
            exit 1
          fi
     
          pip install --target=./ requests cryptography cffi
          find . -type d -name '*dist-info' -exec rm -rf {} +
          zip -r code.zip .
          python sync.py

      - name: Process Auto-Sign-2 App and Deploy to HWAWAI FC
        run: |
          cd veiled-journeys/Auto-Sign-2
          pip install --target=./ requests rsa pyyaml
          find . -type d -name '*dist-info' -exec rm -rf {} +
          zip -r code.zip .
          python sync.py
