name: Video Compression Workflow

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/apt/archives
            ~/.cache/pip
          key: ${{ runner.os }}-deps-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Setup Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Clone veiled-journeys repository
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://x-access-token:${PAT}@github.com/Jyf0214/veiled-journeys.git

      - name: Install Python requirements
        run: |
          # 假设我们最终的脚本叫 file_manager.py，并且它的依赖在 requirements.txt 中
          pip install -r veiled-journeys/requirements.txt

      - name: Download One Video File from Directory
        run: |
          mkdir -p video_work
          cd veiled-journeys
          # 注意：这里的 webdav_download.py 应该和您的下载逻辑匹配
          python webdav_download.py -a="MyVideos/" -b="../video_work/" -c=1
          cd ..

      - name: Process and Compare Video
        id: process
        run: |
          cd video_work
          ORIGINAL_FILE=$(find . -type f -name "*.mp4" -print -quit)
          
          if [ -z "$ORIGINAL_FILE" ]; then
            echo "::error::No .mp4 file found in the downloaded content!"
            exit 1
          fi
          
          ORIGINAL_FILENAME=$(basename "$ORIGINAL_FILE")
          COMPRESSED_FILE="compressed_${ORIGINAL_FILENAME}"
          
          echo "Processing file: $ORIGINAL_FILENAME"
          echo "Starting FFmpeg encoding with high-efficiency settings..."
          
          ffmpeg -i "$ORIGINAL_FILE" -c:v libx265 -preset fast -crf 16 -threads 16 -tag:v hvc1 -c:a copy "$COMPRESSED_FILE"
          
          ORIGINAL_SIZE=$(stat -c%s "$ORIGINAL_FILE")
          COMPRESSED_SIZE=$(stat -c%s "$COMPRESSED_FILE")
          
          echo "Original size: $ORIGINAL_SIZE bytes"
          echo "Compressed size: $COMPRESSED_SIZE bytes"
          
          if [ "$ORIGINAL_SIZE" -le "$COMPRESSED_SIZE" ]; then
            echo "Compressed file is not smaller. Keeping original."
            rm "$COMPRESSED_FILE"
            mv "$ORIGINAL_FILE" "final_output.mp4"
            echo "final_file=video_work/final_output.mp4" >> $GITHUB_OUTPUT
          else
            echo "Compressed file is smaller. Keeping compressed version."
            rm "$ORIGINAL_FILE"
            mv "$COMPRESSED_FILE" "final_output.mp4"
            echo "final_file=video_work/final_output.mp4" >> $GITHUB_OUTPUT
          fi
          cd ..

      # [--- 这是被修改的核心步骤 ---]
      - name: Upload to GoFile and Update List (Silent)
        run: |
          # 运行我们最终的多功能脚本 file_manager.py
          # 1. 使用 upload 子命令
          # 2. --list-file 定义了在WebDAV上要更新的任务清单文件名
          # 3. > /dev/null 2>&1 将所有标准输出和错误输出重定向到空设备，实现“静默”运行
          python veiled-journeys/file_manager.py upload \
            --file "${{ steps.process.outputs.final_file }}" \
            --list-file "compressed_videos_list.txt" 
