name: Auto Sign
on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Clone private repository
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://x-access-token:${PAT}@github.com/Jyf0214/veiled-journeys.git

      - name: Install dependencies globally
        run: |
          pip install -r veiled-journeys/requirements.txt

      - name: Run veiled-journeys scripts
        env:
          GitHub_Actions: true
          TOTKEN: ${{ secrets.TOKEN }}
          SUBJECT: ${{ secrets.SUBJECT }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          Git_EMAIL: ${{ secrets.TO_EMAIL }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          PHONE: ${{ secrets.PHONE }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          cd veiled-journeys
          python skyland.py
          python smtp.py
          python bingapi.py
          python git.py

      - name: Process Skland App and Deploy to HUAWEI FC
        run: |
          # 进入目标目录
          cd veiled-journeys/Skland

          # 列出当前目录的文件以便调试
          ls

          # 检查 TOKEN.txt 文件是否存在
          if [ ! -f "./TOKEN.txt" ]; then
            echo "Error: TOKEN.txt does not exist."
            exit 1
          fi

          # 验证 TOKEN.txt 文件内容是否为空
          if [ ! -s "./TOKEN.txt" ]; then
            echo "Error: TOKEN.txt is empty."
            exit 1
          fi

          # 验证 TOKEN.txt 文件内容格式（示例：检查是否为 Base64 编码）
          if ! grep -qE '^[A-Za-z0-9+/=]+$' "./TOKEN.txt"; then
            echo "Error: TOKEN.txt contains invalid characters."
            exit 1
          fi

          # 内容合法，执行 Python 脚本
          python sync.py
