name: Auto Sign
on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies globally
        run: |
          python -m pip install --upgrade pip
          pip install requests cryptography resend pyyaml rsa huaweicloudsdkfunctiongraph

      - name: Clone private repository
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://x-access-token:${PAT}@github.com/Jyf0214/veiled-journeys.git

      - name: Run scripts
        env:
          GitHub_Actions: true
          TOKEN: ${{ secrets.TOKEN }}
          SUBJECT: ${{ secrets.SUBJECT }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          Git_EMAIL: ${{ secrets.TO_EMAIL }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: |
          cd veiled-journeys
          python skyland.py
          python smtp.py
          python bingapi.py
          python git.py
          cd Auto-Sign
          if [ ! -d "./packages" ]; then
            mkdir ./packages
            echo "Created packages directory"
          else
            echo "Packages directory already exists"
          fi
          pip install --target=./packages requests rsa pyyaml resend
          zip -r code.zip .
          python sync.py