name: Log Script and Random String Generator

on:
  schedule:
    - cron: '0 4 * * 5'  # 每周五 UTC 4点（即 UTC+8 的中午12点）
  workflow_dispatch:  # 支持手动触发工作流

jobs:
  log_script:
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      TOEMAIL: ${{ secrets.TOEMAIL }}
      MAIL_SUBJECT: ${{ secrets.MAIL_SUBJECT }}
      # 如果有其他需要的环境变量，可以继续在这里添加

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests  # 安装依赖包

      - name: Run log script
        run: |
          python src/closure.py  # 运行日志脚本

      - name: Generate random string
        id: random_string
        run: |
          RANDOM_STRING=$(openssl rand -base64 12)  # 生成12个字符的随机字符串
          echo "Generated string: $RANDOM_STRING"
          echo "random_string=$RANDOM_STRING" >> $GITHUB_ENV  # 将生成的随机字符串保存到环境变量中

      - name: Save random string to a file
        run: |
          echo ${{ env.random_string }} > random_string.txt  # 将随机字符串保存到文件中

      - name: Commit and push random string
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          message: 'Add generated random string'
          add: 'random_string.txt'
          push: true  # 自动推送更改
          branch: 'gh-pages'  # 推送到指定分支，如 gh-pages

      - name: Push changes to repository
        run: |
          git push origin gh-pages  # 确保推送到正确的分支