name: Log Script and Random String Generator

on:
  schedule:
    - cron: '0 4 * * 5'  # 每周五 UTC 4点（即 UTC+8 的中午12点）
  workflow_dispatch:  # 支持手动触发工作流

jobs:
  log_script:
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      TOEMAIL: ${{ secrets.TOEMAIL }}
      MAIL_SUBJECT: ${{ secrets.MAIL_SUBJECT }}
      ACCOUNTS: ${{ secrets.ACCOUNTS }}
      # 如果有其他需要的环境变量，可以继续在这里添加

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests  # 安装依赖包

      - name: Generate Random String and Save to TXT
        run: |
          python -c "import random; import string; random_string = ''.join(random.choices(string.ascii_letters + string.digits, k=16)); with open('random_string.txt', 'w') as f: f.write(random_string)"  # 生成16位随机字符串并保存为txt

      - name: Run log script
        run: |
          python src/closure.py  # 运行日志脚本

      - name: Run git push script
        run: |
          python src/push.py  # 执行 gitpush 脚本