name: Discord-Gemini-Chatbot Auto Compress

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ---------- 1. 检出当前仓库 ----------
      - name: Checkout workflow repository
        uses: actions/checkout@v4

      # ---------- 2. 系统依赖 ----------
      - name: Install system packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            curl gpg git ffmpeg mediainfo htop \
            fonts-noto-cjk fonts-noto-color-emoji ttf-mscorefonts-installer
          echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | \
            sudo debconf-set-selections
          sudo fc-cache -fv

      # ---------- 3. Python 环境 ----------
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python packages
        run: |
          pip install --upgrade pip
          pip install numpy onnxruntime pandas pillow requests

      # ---------- 4. 拉取私有仓库 ----------
      - name: Clone private repository
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://x-access-token:${PAT}@github.com/Jyf0214/veiled-journeys.git

      # ---------- 5. 安装项目依赖 ----------
      - name: Install project requirements
        run: |
          pip install -r veiled-journeys/requirements.txt
          pip install -r veiled-journeys/Discord-Gemini-Chatbot/requirements.txt

      # ---------- 6. 下载 NSFW 识别模型 ----------
      - name: Download tagger model
        run: |
          mkdir -p veiled-journeys/tagger_model
          wget -O veiled-journeys/tagger_model/model.onnx \
            https://huggingface.co/SmilingWolf/wd-eva02-large-tagger-v3/resolve/main/model.onnx

# ---------- 8. 启动 Discord Bot ----------
      - name: Start Discord bot
        env:
          GOOGLE_AI_KEY: ${{ secrets.GOOGLE_AI_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: |
          cd veiled-journeys/Discord-Gemini-Chatbot
          nohup python bot.py > bot.log 2>&1 &
         

      # ---------- 7. 运行 NSFW 检测 ----------
      - name: Run NSFW detection
        run: |
          cd veiled-journeys
          python detect_nsfw.py

      # ---------- 8. 启动 Discord Bot ----------
      - name: Start Discord bot
        env:
          GOOGLE_AI_KEY: ${{ secrets.GOOGLE_AI_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: |
          cd veiled-journeys
          sleep $((5*3600 + 50*60))
          pkill -f bot.py
