name: Discord-Gemini-Chatbot Auto Compress

on:
  workflow_dispatch:


jobs:
  install_and_run_job:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1: 检出运行工作流的代码库
      - name: Checkout workflow repository
        uses: actions/checkout@v4

      # 步骤 2: 安装基础工具
      - name: Install base tools (curl, gpg, git)
        run: sudo apt-get update && sudo apt-get install -y curl gpg git

   
      - name: Clone private repository (veiled-journeys)
        env:
          PAT: ${{ secrets.PAT }}
        run: git clone https://x-access-token:${PAT}@github.com/Jyf0214/veiled-journeys.git

      - name: Install Python dependencies
        run: pip install -r veiled-journeys/requirements.txt

     
      - name: Install image optimization tools
        run: pip install -r veiled-journeys/Discord-Gemini-Chatbot/requirements.txt

      - name: Upload Compressed to Web
        env:
          GOOGLE_AI_KEY: ${{ secrets.GOOGLE_AI_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: |
          cd veiled-journeys/Discord-Gemini-Chatbot
          nohup python bot.py > /dev/null 2>&1 & sleep $((5*3600+50*60)) && pkill -f bot.py

jobs:
  detect_nsfw:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg mediainfo htop 
          sudo apt-get install -y fonts-noto-cjk fonts-noto-color-emoji
          echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections
          sudo apt-get install -y ttf-mscorefonts-installer
          sudo fc-cache -fv
          pip install numpy onnxruntime pandas pillow requests

      - name: Clone Repository
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://x-access-token:${PAT}@github.com/Jyf0214/veiled-journeys.git

      - name: Create Processor Script
        run: |
          cd veiled-journeys/tagger_model/
          wget -O model.onnx "https://huggingface.co/SmilingWolf/wd-v1-4-swinv2-tagger-v2/resolve/main/model.onnx"


      - name: Run Processor Script
        run: |
          cd veiled-journeys
          python detect_nsfw.py
          