name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 在 main 分支推送时触发

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # 项目使用的 Node.js 版本，可根据需要调整

    - name: Cache Node modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: yarn install  # 使用 Yarn 安装依赖

    - name: Build project
      run: yarn build  # Vite 默认构建命令

    - name: Copy SVG files to output directory
      run: |
        mkdir -p dist/assets  # 确保 dist/assets 目录存在
        cp -r src/assets/*.{svg,jpg,png,gif} dist/assets/
        cp -r src/assets/*.json dist/assets/


    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Vite 默认构建输出目录
        cname: jyf20100214.giize.com