name: Deploy to GitHub Pages & Sync to GitLab

on:
  push:
    branches:
      - main  # 当 main 分支有推送时触发

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Cache Node modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: yarn build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: jyf20100214.giize.com

  sync-repositories:
    runs-on: ubuntu-latest
    needs: build-deploy
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get repository info
        id: repo-info
        run: |
          OWNER=$(echo "$GITHUB_REPOSITORY" | cut -d'/' -f1)
          REPO=$(echo "$GITHUB_REPOSITORY" | cut -d'/' -f2)
          echo "owner=$OWNER" >> $GITHUB_OUTPUT
          echo "repo=$REPO" >> $GITHUB_OUTPUT

      - name: Configure Git
        run: |
          git config --global user.name "Jyf0214"
          git config --global user.email "actions@users.noreply.github.com"

      - name: Sync to GitLab (极狐香港站)
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@gitlab.hk/${{ steps.repo-info.outputs.owner }}/${{ steps.repo-info.outputs.repo }}.git"
          git push --all --force gitlab
          git push --tags --force gitlab
          echo "✅ Synced to GitLab (gitlab.hk)"

      - name: Sync to GitCode
        env:
          GITCODE_TOKEN: ${{ secrets.GITCODE_TOKEN }}
        run: |
          git remote add gitcode "https://${{ steps.repo-info.outputs.owner }}:${GITCODE_TOKEN}@gitcode.com/${{ steps.repo-info.outputs.owner }}/${{ steps.repo-info.outputs.repo }}.git"
          git push --all --force gitcode
          git push --tags --force gitcode
          echo "✅ Synced to GitCode"
