jobs:
  your_job:  # Replace with your job's name
    runs-on: ubuntu-latest  # Or your preferred runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Or your desired Python version

      - name: Install Dependencies (if needed)
        run: |
          cd veiled-journeys
          pip install -r requirements.txt  # If you have a requirements.txt file

      - name: Upload Compressed to Web
        run: |
          cd veiled-journeys
          python 4.py

      - name: Check for finished.task and Run 4_img.py
        run: |
          cd veiled-journeys
          if [ -f finished.task ]; then
            echo "finished.task found! Running 4_img.py..."
            python 4_img.py
          else
            echo "finished.task not found. Skipping 4_img.py..."
          fi