name: Web Auto Compress

on:
  workflow_dispatch:

jobs:
  auto-sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pm2 globally
        run: npm install -g pm2

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache apt packages
        uses: actions/cache@v3
        with:
          path: /usr/local/apt-cache
          key: ${{ runner.os }}-apt-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Update and install apt packages
        run: |
          sudo mkdir -p /usr/local/apt-cache
          sudo apt-get update
          sudo apt-get install -y ffmpeg optipng jpegoptim fonts-wqy-microhei
          sudo cp -r /var/cache/apt/* /usr/local/apt-cache

      - name: Clone private repository
        env:
          PAT: ${{ secrets.PAT }}
        run: git clone https://x-access-token:${PAT}@github.com/Jyf0214/veiled-journeys.git

      - name: Install dependencies globally
        run: pip install -r veiled-journeys/requirements.txt

      - name: Test veiled-journeys App
        run: |
          cd veiled-journeys
          python 3.py

      - name: Process Video 
        env:
          PAT_1: ${{ secrets.PAT_1 }}
        run: |
          cd veiled-journeys
          video="$(echo *.mp4)"; sub="$(echo *.srt)"; ffmpeg -i "$video" -vf "subtitles=$sub:force_style='Fontname=WenQuanYi Micro Hei'" -c:v libx264 -c:a copy -threads 8 -y -f mp4 "${video%.mp4}.compressed.mp4"

      - name: Upload Compressed to Web
        run: |
          cd veiled-journeys
          python 4.py