name: Web Auto Compress

on:
  workflow_dispatch:

jobs:
  # 自动测试作业
  auto-sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pm2 globally
        run: npm install -g pm2

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Clone private repository
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://x-access-token:${PAT}@github.com/Jyf0214/veiled-journeys.git

      - name: Install dependencies globally
        run: |
          pip install -r veiled-journeys/requirements.txt
          sudo apt-get update
          sudo apt-get install -y ffmpeg 

      - name: Test veiled-journeys App
        run: |
          cd veiled-journeys
          python 3.py

      - name: Process Video 
        run: |
          cd veiled-journeys
          pm2 start "python iloveapi_img_plus.py" --name "img-python-app"
          chmod +x compress.sh
          ./compress.sh

      - name: Upload Compressed to Web
        id: upload_step # Add an ID so we can check results later
        run: |
          cd veiled-journeys
          python 4.py

      - name: Check for finished.task and Run 4_img.py
        if: success()  # Only run if the previous step was successful
        run: |
          cd veiled-journeys
          while true; do
            if [ -f finished.task ]; then
              echo "finished.task found! Running 4_img.py..."
              python 4_img.py
              break  # 找到文件后退出循环
            else
              echo "finished.task not found. Waiting..."
              sleep 5  # 等待一段时间（例如5秒）后再次检查
            fi
          done