name: Picture Auto Compress

on:
  push:
    branches:
      - main  # 在 main 分支推送时触发
  workflow_dispatch:  # 支持手动触发

jobs:
  auto-sign:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 设置 Python 环境
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 全局安装 pm2
      - name: Install pm2 globally
        run: npm install -g pm2

      # 缓存 pip 依赖
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 缓存 apt 包
      - name: Cache apt packages
        uses: actions/cache@v3
        with:
          path: /usr/local/apt-cache
          key: ${{ runner.os }}-apt-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      # 更新并安装 apt 包
      - name: Update and install apt packages
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg optipng jpegoptim fonts-wqy-microhei

      # 克隆私有仓库
      - name: Clone private repository
        env:
          PAT: ${{ secrets.PAT }}
        run: git clone https://x-access-token:${PAT}@github.com/Jyf0214/veiled-journeys.git

      # 全局安装依赖
      - name: Install dependencies globally
        run: pip install -r veiled-journeys/requirements.txt

      # 测试 veiled-journeys 应用
      - name: Test veiled-journeys App
        run: |
          cd veiled-journeys
          pip install torch==1.10.0+cu102 torchvision==0.11.0+cu102 -f https://download.pytorch.org/whl/torch_stable.html

          

      # 处理视频
      - name: Process Video
        env:
          PAT_1: ${{ secrets.PAT_1 }}
        run: |
          cd veiled-journeys
          git clone https://github.com/xinntao/Real-ESRGAN.git
          python Picture_download.py
          cd Real-ESRGAN
          pip install basicsr
          pip install facexlib
          pip install gfpgan
          pip install -r requirements.txt
          python setup.py develop
          # download model
          wget https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.2.4/RealESRGAN_x4plus_anime_6B.pth -P weights
          # inference
          pip uninstall numpy
          pip install numpy==1.22.4
          pip install torch==1.10.0+cu102 torchvision==0.11.0+cu102 -f https://download.pytorch.org/whl/torch_stable.html
          pip install torch==1.10.0 torchvision==0.11.0 --extra-index-url https://download.pytorch.org/whl/cpu
          python inference_realesrgan.py -n RealESRGAN_x4plus_anime_6B -i input_images

      # 上传压缩后的文件到 Web
      - name: Upload Compressed to Web
        run: |
          cd veiled-journeys
          python Picture_upload.py
          

