name: Pictures Auto Compress

on:
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest  # 使用最新的稳定 Ubuntu 版本
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache apt packages
        uses: actions/cache@v3
        with:
          path: /usr/local/apt-cache
          key: ${{ runner.os }}-apt-${{ hashFiles('veiled-journeys/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Update and install apt packages
        run: |
          sudo mkdir -p /usr/local/apt-cache
          sudo apt-get update
          sudo apt-get install -y ffmpeg megatools
          sudo cp -r /var/cache/apt/* /usr/local/apt-cache

      - name: Clone private repository
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://x-access-token:${PAT}@github.com/Jyf0214/veiled-journeys.git

      - name: Install Python dependencies
        run: |
          pip install -r veiled-journeys/requirements.txt

      - name: Test veiled-journeys App
        run: |
          ffmpeg -h encoder=libx264
          cd veiled-journeys
          chmod +x download_mega_video.sh
          python webdav_download.py -a="Pictures/a4_layout/" -b="./output_images/" -c=114514

      - name: Process 
        run: |
          cd veiled-journeys
          chmod +x compress.sh
          python a4_layout.py
          python iloveapi_img_plus.py	

      - name: Upload Compressed to Web
        run: |
          cd veiled-journeys
          python koofr_check_and_upload.py