name: Pictures Auto Compress

on:
  workflow_dispatch:


jobs:
  install_and_run_job:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1: 检出运行工作流的代码库
      - name: Checkout workflow repository
        uses: actions/checkout@v4

      # 步骤 2: 安装基础工具
      - name: Install base tools (curl, gpg, git)
        run: sudo apt-get update && sudo apt-get install -y curl gpg git

      # 步骤 3: 安装 cloudflared
      - name: Create keyrings directory
        run: sudo mkdir -p --mode=0755 /usr/share/keyrings
      - name: Download Cloudflare GPG key
        run: curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo gpg --dearmor --yes -o /usr/share/keyrings/cloudflare-main.gpg
      - name: Add Cloudflare APT repository
        run: echo "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflared.list
      - name: Update package list and install cloudflared
        run: sudo apt-get update && sudo apt-get install -y cloudflared
      - name: Verify cloudflared installation
        run: cloudflared --version

      # 步骤 4: 克隆包含 Alist 配置的私有仓库
      - name: Clone private repository (veiled-journeys)
        env:
          PAT: ${{ secrets.PAT }}
        run: git clone https://x-access-token:${PAT}@github.com/Jyf0214/veiled-journeys.git

      - name: Install Python dependencies
        run: pip install -r veiled-journeys/requirements.txt

      # 步骤 9: 安装 Alist 可能需要的其他依赖 (如果需要, 现在是第 9 步)
      - name: Install image optimization tools
        run: sudo apt-get update && sudo apt-get install -y jpegoptim optipng

      # 步骤 10: 设置脚本执行权限 (现在是第 10 步)
      - name: Set script execution permission
        run: chmod +x veiled-journeys/process_loop.sh

      # 步骤 11: 启动 Cloudflared Tunnel (现在是第 11 步)
      - name: Start Cloudflared Tunnel in background
        working-directory: ./veiled-journeys
        run: |
          echo "Starting Cloudflared tunnel..."
          nohup cloudflared tunnel --config .cloudflared/config.yml run > cloudflared.log 2>&1 &
          sleep 5
   
      - name: Clone private repository
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://x-access-token:${PAT}@github.com/Jyf0214/veiled-journeys.git

      - name: Install Python dependencies
        run: |
          pip install -r veiled-journeys/requirements.txt

      - name: Test veiled-journeys App
        run: |
          ffmpeg -h encoder=libx264
          cd veiled-journeys
          chmod +x download_mega_video.sh
          python webdav_download.py -a="Pictures/a4_layout/" -b="./input_images/" -c=741210248504952

      - name: Process 
        run: |
          cd veiled-journeys
          chmod +x compress.sh
          python a4_layout.py
          python iloveapi_img_plus.py	

      - name: Upload Compressed to Web
        run: |
          cd veiled-journeys
          python koofr_check_and_upload.py