name: Web Auto Compress

on:
  workflow_dispatch:

jobs:
  # 自动测试作业
  auto-sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Clone private repository
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://x-access-token:${PAT}@github.com/Jyf0214/veiled-journeys.git

      - name: Install dependencies globally
        run: |
          pip install -r veiled-journeys/requirements.txt
          sudo apt-get update
          sudo apt-get install -y ffmpeg 
          
      - name: Test veiled-journeys App
        run: |
          cd veiled-journeys
          python 3.py

      - name: Process Video 
        run: |
          cd veiled-journeys
          ffmpeg -i input.mp4 -vf "scale=1080:-2" -c:v libx264 -crf 3 -preset veryslow -threads 16 output.mp4


      - name: Upload Compressed to Web
        run: |
          cd veiled-journeys
          python 4.py


